### ISSUE TITLE
Add hospitalisations and ICU treatments to the scraping

### ISSUE THREAD

**Issue by mhoehle** [jakubvalenta/covid-berlin-data#1]
Thanks for providing this ressource! Would it be possible to add the number of hospitalizations and ICU treatments to the scrape. These are also included in the (textual part of the) press releases AFAIK?

**Comment by jakubvalenta** [comment]
Great idea!

I've updated the scraper. You can now find the data in a new CSV file https://github.com/jakubvalenta/covid-berlin-data/blob/master/covid_berlin_data_incl_hospitalized.csv

I didn't put the data in the existing CSV https://github.com/jakubvalenta/covid-berlin-data/blob/master/covid_berlin_data.csv because some people are already using this file and adding new columns to it might break their systems. This old CSV will continue being updated though, just without the new columns.

**Comment by mhoehle** [comment]
Thanks very much for this additional feature!
